### ISSUE TITLE
non-descriptive Error in SHA2 when installing

### ISSUE THREAD

**Issue by abdurrahman-nasr** [buckie/juno#25]
I'm facing a wierd exception about SHA2 installation, when calling "cabal install". the description ends with ExitFailure1 !!

Attached is the log file
[sha2.txt](https://github.com/buckie/juno/files/283764/sha2.txt)

**Comment by buckie** [comment]
This is not a Juno issue, but an 'installing sha2 on windows issue' and is likely caused by Windows. I have no plans to ever actively support Windows for Juno through would be happy to include info about how to build it for windows if you provide it to me. 

I'd recommend first attempting to build Juno via stack because it's a quick test to perform and may just work. If that fails I'd personally give up, install VMWare w/ Ubuntu and play with Juno there.

If you really feel like solving it @cartazio may have some ideas.

**Comment by cartazio** [comment]
The error log seems to be related to related to certain c types not being supported by whatever c compiler you're using.  So it's a sha package issue.  Report it there.  Probably fixed in some newer version of that package that's not in your stack version. Or it's a big you should report to them.

**Comment by cartazio** [comment]
*bug

**Comment by abdurrahman-nasr** [comment]
Thank you guys for the support. I'm gonna trace the bug there at SHA
